### ISSUE TITLE
HFS with cv2 not working

### ISSUE THREAD

**Issue by EladWarshawsky** [1999kevin/INR-Partition#1]
I encountered an issue while trying to run the hfs_domain_decomposition function. Here are the details:

Error Message:

python
Copy code
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 53
     48 #     plt.imshow(labels_out)
     49 #     plt.show()
     50     # return res
     51     return labels_out
---> 53 labels_out = hfs_domain_decompostion(image,patch_num=9)
     55 plt.imshow(labels_out)
     56 plt.show()

Cell In[20], line 31, in hfs_domain_decompostion(img, patch_num)
     27 def hfs_domain_decompostion(img,patch_num=4):
     28     # plt.imshow(img)
     29     # plt.show()
     30     # print(img.shape)
---> 31     engine = cv2.hfs.HfsSegment_create(img.shape[0], img.shape[1])
     33     res = engine.performSegmentGpu(img, False)
     34     # print('heads:', np.max(res))
     35     # plt.imshow(res)
     36     # plt.show()
     37     # return res
     38     # print('s')

AttributeError: module 'cv2.hfs' has no attribute 'HfsSegment_create'
Steps to Reproduce:

Clone the repository.
Install the dependencies using requirements.txt.
Execute the hfs_domain_decomposition function with specified parameters.
Expected Behavior:
The function should run successfully without any attribute errors.

Additional Information:

Python version: [e.g., Python 3.8]
OpenCV version: [e.g., OpenCV 4.5.1]
Operating System: [e.g., Linux]
Note:
It seems like the HfsSegment_create attribute is missing in the cv2.hfs module. Please provide guidance on how to resolve this issue. I know that this seems like a trivial issue, but I'd be happy if you could help.

**Comment by 1999kevin** [comment]
Hi, HFS should be a function in the OpenCV package. It should not cause error if you have the correct OpenCV installation. In our implementation, we use ```opencv-contrib-python==4.8.1.78```.
