### ISSUE TITLE
The method is very similar to MINER and ACORN, and its generality and performance are inferior to them...

### ISSUE THREAD

**Issue by weixiang-zhang** [1999kevin/INR-Partition#2]
Thanks for your contribution. I have a few questions regarding the proposed work.

This paper uses segmentation to partition the image and apply different INRs to different parts. However, when I implemented this repository, the performance of grid-based and segment-based methods was very similar. The grid-based partition method is quite similar to MINER and Acorn, which suggests limited novelty in the proposed work. Most importantly, the method was not compared with MINER and Acorn, which I believe would be very difficult to surpass.

[1] ACORN: Adaptive coordinate networks for neural representation. | TOG 2021
[2] MINER: Multiscale Implicit Neural Representation | ECCV 2022

**Comment by weixiang-zhang** [comment]
Another limitation is that both MINER and ACORN can be applied to other modalities, such as 3D shapes, whereas this work is limited to implementation on images.

**Comment by 1999kevin** [comment]
Hi, thank you for your attention to our work. 

The contribution of this paper involves three parts: 1) a theoretical and empirical view of the exponential-increase hypothesis, 2) a simple partition-based MLP architecture, and 3) its application on both learning INRs and learning-to-learn INRs. 

Our key point is to illustrate the potential reason why partition helps to improve the convergence of INRs, which motivates us to design a simple partition-based MLP architecture. Indeep, as we have discussed in the related work of the paper, we admit that it is hard to compare our simple partition-based MLP architecture with more complex INR architectures such as ACORN and MINER. However, it helps us to conduct an ablation study about how and why simple partition helps to improve the convergence of INRs, which is not illustrated in any other papers. And, thanks to its simplicity, we can generalize the simple partition-based MLP architecture to the meta-learning framework, which is impossible for the complex ACORN and MINER.

As for other modalities, We have adapted our model to 3D surface and NeRF. See paper supplementary at https://openaccess.thecvf.com/content/ICCV2023/supplemental/Liu_Partition_Speeds_Up_ICCV_2023_supplemental.pdf.

**Comment by weixiang-zhang** [comment]
Thank you for your reply. I have another question: why can't complex MINER use a meta-learning framework?

**Comment by 1999kevin** [comment]
During training, both MINER and ACORN require pruning those MLPs that have small mean square error (MSE) to focus on more complex regions, making them efficient for fitting a single complex signal. However, in the context of meta-learning frameworks for multiple signals, it's challenging to figure out which regions to prune for different signals with very limited optimization steps (for example, only 3 steps in our implementation). 

In contrast, our method relies solely on the simple partition mask (Grid or semantic segmentation) that can be obtained before optimization, providing a prior for efficiently partitioning the entire domain.

If you find our project helpful, please feel free to star it.

**Comment by 1999kevin** [comment]
Hi, if you do not have further questions, I'll close this issue.

**Comment by weixiang-zhang** [comment]
Thanks for your reply. This paper & repo is very helpful and I have cited the paper in my recent pubs.
Looking forward to your new work!

**Comment by 1999kevin** [comment]
> Thanks for your reply. This paper & repo is very helpful and I have cited the paper in my recent pubs. Looking forward to your new work!

Sorry for the late reply, and thank you very much for citing! I have also read your AAAI and CVPR papers regarding efficient INR training. They are both effective and straightforward! I'd like to cite these papers in my following works.

Currently, I'm moving to generalizable INR with feed-forward hyper-network and its application on various modalities and downstream tasks. Please see our recent works published in [ECCV2024](https://arxiv.org/pdf/2407.15355), [KDD2025](https://arxiv.org/pdf/2411.11641) and [AAAI2025](https://arxiv.org/abs/2501.02427). I find that you're maintaining a GitHub repo for [Recent-Progress-of-INR](https://github.com/zwx-open/Recent-Progress-of-INR). It would be our honor if you find our papers helpful and include these works.
